[features]
seeds = false
skip-lint = false

[programs.devnet]
fundrr = "FUNDRR_PROGRAM_ID"

[programs.mainnet-beta]
fundrr = "FUNDRR_PROGRAM_ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"